### ISSUE TITLE
Fps calculation in run_dqn, and one problem on gpu selection

### ISSUE THREAD

**Issue by Elfits** [keiohta/tf2rl#66] opened 2019-12-11 10:25 UTC
Hi Ohta,
I am here again.
When run `run_dqn.py` in `examples`, an error occurred.

>   File "F:/tf2rl_shop2/tf2rl-master/examples/run_dqn.py", line 46, in <module>
    trainer()
  File "E:\anaconda\lib\site-packages\tf2rl\experiments\trainer.py", line 102, in __call__
    fps = episode_steps / (time.time() - episode_start_time)
ZeroDivisionError: float division by zero

However, sometimes it can pass without errors.

Another question is about the gpu selection.
Also in `run_dqn.py` (and any other examples), gpu is selected by `parser.set_defaults(gpu=-1)`
But in `policy_base.py`, gpu is set to 0 in `__init__` of class `Policy`.
I wonder whether `parser.set_defaults(gpu=-1)` works. This may be a stupid question because I am actually a beginner.

**Comment by Elfits** [comment] 2019-12-11 10:38
Clearly, when cancelling the output of fps, it works out.

**Comment by yamada-github-account** [comment] 2019-12-11 12:01
I guess bad precision of time measuring is (one of) the reason.

---

`time.time()` does not always have good precision.
https://docs.python.org/3/library/time.html#time.time
https://stackoverflow.com/questions/1938048/high-precision-clock-in-python


Probably, it is better to use other newer functions;
*  `time.perf_counter()` : Highest precision, including sleep (system-wide real time)
*  `time.process_time()` : Not includes sleep (only this process)
*  `time.monotonic()` : Never go back and safest, including sleep (system-wide real time)

https://docs.python.org/3/library/time.html#time.perf_counter
https://docs.python.org/3/library/time.html#time.process_time
https://docs.python.org/3/library/time.html#time.monotonic

---

There might be other reasons, too.

**Comment by keiohta** [comment] 2019-12-12 00:59
Thank you @Elfits for your report, and @yamada-github-account for useful comment.
As suggested, I replace "time.time" with "time.perf_counter", and the bug should be fixed now.

If I remember correctly, you're using tf2rl on Windows, and I guess this seems to be the reason why this bug occurred. According to [this post](https://stackoverflow.com/questions/1938048/high-precision-clock-in-python), the accuracy of clock on Windows is ~16ms, whereas ~1ms on Mac and Ubuntu. This is why I cannot reproduce this bug on my Mac machine.

Anyway, please try latest version and let me know the result.
Thanks!

**Comment by Elfits** [comment] 2019-12-12 08:29
By using `time.perf_counter` it works correctly now.
I also had a (maybe stupid) question:

> Another question is about the gpu selection.
Also in run_dqn.py (and any other examples), gpu is selected by parser.set_defaults(gpu=-1)
But in policy_base.py, gpu is set to 0 in __init__ of class Policy.
I wonder whether parser.set_defaults(gpu=-1) works. This may be a stupid question because I am actually a beginner.

**Comment by yamada-github-account** [comment] 2019-12-12 11:41
@Elfits Thanks for your great contribution! This is very helpful.

---

Just my opinion.

Your question seems to be unrelated with the main topic of this issue (`ZeroDivisionError`), 
so that it might be better to close this issue and create a new one focusing your question.

It might be annoying for you, but I think this can be easier for others to find information.
We would like to keep this repository organized.

**Comment by Elfits** [comment] 2019-12-12 12:08
> @Elfits Thanks for your great contribution! This is very helpful.
> 
> Just my opinion.
> 
> Your question seems to be unrelated with the main topic of this issue (`ZeroDivisionError`),
> so that it might be better to close this issue and create a new one focusing your question.
> 
> It might be annoying for you, but I think this can be easier for others to find information.
> We would like to keep this repository organized.

Sure!
Please close this issue, and I may open a new one later. : ）

**Closed** 2019-12-12 18:25 UTC
